-- ==============================================================================
-- OMNISTORE CARTAGENA - ESQUEMA PROFESIONAL DE BASE DE DATOS POSTGRESQL
-- ==============================================================================
-- Plataforma E-Commerce OmniStore + Panel Administrativo + Tienda Pública
-- Exclusivo para Cartagena de Indias, Bolívar, Colombia (Moneda: COP $)
-- Compatible con Supabase PostgreSQL (https://supabase.com) y PostgreSQL 14+
-- ==============================================================================

-- EXTENSIONES NECESARIAS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 1. TABLA DE USUARIOS Y PERFILES (users)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('admin', 'vendor', 'support', 'accountant', 'customer', 'user')),
    avatar TEXT DEFAULT './assets/images/avatar-placeholder.svg',
    phone TEXT,
    document_type TEXT DEFAULT 'CC', -- 'CC', 'NIT', 'CE', 'PASAPORTE'
    document_number TEXT,
    address TEXT,
    neighborhood TEXT, -- Barrio en Cartagena (Bocagrande, Manga, Crespo, etc.)
    city TEXT NOT NULL DEFAULT 'Cartagena de Indias',
    department TEXT NOT NULL DEFAULT 'Bolívar',
    country TEXT NOT NULL DEFAULT 'Colombia',
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending', 'suspended')),
    last_login TIMESTAMPTZ
);

-- ==============================================================================
-- 2. LIBRETA DE DIRECCIONES DE CLIENTES (user_addresses)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    recipient_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    neighborhood TEXT NOT NULL,
    address_line TEXT NOT NULL,
    details TEXT, -- Apto, casa, conjunto, etc.
    city TEXT NOT NULL DEFAULT 'Cartagena de Indias',
    department TEXT NOT NULL DEFAULT 'Bolívar',
    zone_code TEXT DEFAULT 'Z1', -- Z1 (Bocagrande/Centro), Z2 (Manga/Crespo), Z3 (El Bosque), Z4 (Turbaco/Mamonal)
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 3. TABLA DE CATEGORÍAS (categories)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    icon TEXT DEFAULT 'bi-grid',
    description TEXT,
    item_count INT DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive'))
);

-- ==============================================================================
-- 4. TABLA DE PRODUCTOS (products)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    sku TEXT UNIQUE NOT NULL,
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    category_slug TEXT DEFAULT 'electronics',
    category_label TEXT DEFAULT 'Tecnología',
    brand TEXT,
    price NUMERIC(12,2) NOT NULL DEFAULT 0.00, -- Precio en Pesos Colombianos (COP)
    original_price NUMERIC(12,2),
    cost_price NUMERIC(12,2),
    discount_percent INT DEFAULT 0,
    stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    stock_left INT DEFAULT 0,
    stock_total INT DEFAULT 0,
    min_stock_alert INT DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'draft', 'out_of_stock', 'archived')),
    rating NUMERIC(3,2) DEFAULT 5.0,
    reviews_count INT DEFAULT 0,
    sales_count INT DEFAULT 0,
    is_flash_deal BOOLEAN DEFAULT FALSE,
    is_best_seller BOOLEAN DEFAULT FALSE,
    has_free_shipping BOOLEAN DEFAULT FALSE,
    badge_text TEXT,
    image TEXT DEFAULT './assets/images/product-placeholder.svg',
    images JSONB DEFAULT '[]'::jsonb,
    colors JSONB DEFAULT '["Predeterminado"]'::jsonb,
    sizes JSONB DEFAULT '[]'::jsonb,
    description TEXT,
    tags JSONB DEFAULT '["cartagena", "tecnologia", "omnistore"]'::jsonb
);

-- ==============================================================================
-- 5. CARRITO DE COMPRAS PERSISTENTE (cart_items)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1 CHECK (quantity > 0),
    selected_color TEXT DEFAULT 'Predeterminado',
    selected_size TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_user_product_variant UNIQUE(user_id, product_id, selected_color, selected_size)
);

-- ==============================================================================
-- 6. TABLA DE CUPONES Y DESCUENTOS (coupons)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    code TEXT UNIQUE NOT NULL,
    discount_type TEXT NOT NULL DEFAULT 'percentage' CHECK (discount_type IN ('percentage', 'fixed', 'free_shipping')),
    discount_value NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    min_order_amount NUMERIC(12,2) DEFAULT 0.00,
    max_uses INT DEFAULT 1000,
    used_count INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMPTZ,
    description TEXT
);

-- ==============================================================================
-- 7. ZONAS Y TARIFAS DE ENVÍO EN CARTAGENA (shipping_zones)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.shipping_zones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zone_code TEXT UNIQUE NOT NULL, -- Z1, Z2, Z3, Z4
    name TEXT NOT NULL,
    neighborhoods JSONB NOT NULL DEFAULT '[]'::jsonb,
    price NUMERIC(10,2) NOT NULL DEFAULT 6500.00, -- COP
    estimated_delivery_time TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 8. TABLA DE PEDIDOS Y VENTAS (orders)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    order_number TEXT UNIQUE NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_phone TEXT,
    customer_doc TEXT,
    shipping_address TEXT NOT NULL,
    shipping_neighborhood TEXT,
    shipping_city TEXT NOT NULL DEFAULT 'Cartagena de Indias',
    shipping_department TEXT NOT NULL DEFAULT 'Bolívar',
    shipping_country TEXT NOT NULL DEFAULT 'Colombia',
    shipping_zone_id BIGINT REFERENCES public.shipping_zones(id) ON DELETE SET NULL,
    payment_method TEXT DEFAULT 'nequi', -- 'card', 'pse', 'nequi', 'daviplata', 'cash'
    payment_status TEXT DEFAULT 'pending' CHECK (payment_status IN ('pending', 'approved', 'rejected', 'refunded')),
    item_count INT NOT NULL DEFAULT 1,
    subtotal NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    discount_amount NUMERIC(12,2) DEFAULT 0.00,
    shipping_cost NUMERIC(12,2) DEFAULT 0.00,
    total NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    coupon_code TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')),
    order_date DATE DEFAULT CURRENT_DATE,
    tracking_number TEXT,
    notes TEXT,
    items JSONB NOT NULL DEFAULT '[]'::jsonb
);

-- ==============================================================================
-- 9. DETALLE NORMALIZADO DE ARTÍCULOS DEL PEDIDO (order_items)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    sku TEXT,
    unit_price NUMERIC(12,2) NOT NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    subtotal NUMERIC(12,2) NOT NULL,
    selected_color TEXT,
    selected_size TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 10. PAGOS Y TRANSACCIONES (payments)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    transaction_reference TEXT UNIQUE NOT NULL,
    payment_gateway TEXT DEFAULT 'wompi', -- 'wompi', 'pse', 'nequi', 'daviplata', 'cash_on_delivery'
    amount NUMERIC(12,2) NOT NULL,
    currency TEXT DEFAULT 'COP',
    status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('pending', 'approved', 'declined', 'voided')),
    gateway_response JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 11. GUÍAS Y DESPACHOS LOGÍSTICOS EN CARTAGENA (shipments)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    tracking_number TEXT UNIQUE NOT NULL,
    carrier TEXT NOT NULL DEFAULT 'Domicilio Express Cartagena',
    carrier_phone TEXT DEFAULT '+57 (605) 665-9000',
    shipping_cost NUMERIC(10,2) DEFAULT 6500.00,
    status TEXT NOT NULL DEFAULT 'preparando' CHECK (status IN ('preparando', 'en_ruta', 'entregado', 'novedad')),
    origin_address TEXT DEFAULT 'CEDI El Bosque / Cra 3 # 7-15 Bocagrande, Cartagena',
    destination_address TEXT NOT NULL,
    destination_neighborhood TEXT,
    estimated_delivery TIMESTAMPTZ,
    shipped_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 12. FACTURACIÓN ELECTRÓNICA DIAN (invoices)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL, -- FE-2026-00482
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    cufe TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    customer_doc TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    customer_city TEXT NOT NULL DEFAULT 'Cartagena de Indias',
    subtotal NUMERIC(12,2) NOT NULL,
    iva NUMERIC(12,2) NOT NULL, -- IVA 19% Colombia
    total NUMERIC(12,2) NOT NULL,
    payment_method TEXT,
    dian_resolution TEXT DEFAULT 'Res. DIAN No. 18764000001 (Rango FE-1 a FE-50000)',
    status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'pending', 'rejected')),
    issued_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 13. TABLA DE RESEÑAS Y CALIFICACIONES (reviews)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL,
    author_email TEXT,
    author_city TEXT DEFAULT 'Bocagrande, Cartagena',
    rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
    title TEXT,
    comment TEXT NOT NULL,
    is_verified_purchase BOOLEAN DEFAULT TRUE,
    helpful_count INT DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'Aprobada' CHECK (status IN ('Aprobada', 'Pendiente', 'Rechazada'))
);

-- ==============================================================================
-- 14. KARDEX Y MOVIMIENTOS DE INVENTARIO (inventory_movements)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    movement_type TEXT NOT NULL CHECK (movement_type IN ('sale', 'restock', 'return', 'adjustment')),
    quantity INT NOT NULL,
    previous_stock INT NOT NULL,
    new_stock INT NOT NULL,
    order_id BIGINT REFERENCES public.orders(id) ON DELETE SET NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 15. ATENCIÓN AL CLIENTE & PQRS (support_tickets)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number TEXT UNIQUE NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    category TEXT DEFAULT 'general' CHECK (category IN ('envios', 'garantias', 'facturacion', 'pedidos', 'general')),
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 16. CONFIGURACIÓN GENERAL DEL SISTEMA (store_settings)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.store_settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- 17. ÍNDICES DE ALTO RENDIMIENTO (OPT-IN PERFORMANCE)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON public.users(role);
CREATE INDEX IF NOT EXISTS idx_users_city ON public.users(city);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category_slug);
CREATE INDEX IF NOT EXISTS idx_products_status ON public.products(status);
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products(sku);
CREATE INDEX IF NOT EXISTS idx_products_price ON public.products(price);
CREATE INDEX IF NOT EXISTS idx_cart_user_id ON public.cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_order_number ON public.orders(order_number);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product_id ON public.order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_payments_order_id ON public.payments(order_id);
CREATE INDEX IF NOT EXISTS idx_shipments_order_id ON public.shipments(order_id);
CREATE INDEX IF NOT EXISTS idx_invoices_order_id ON public.invoices(order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON public.reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_inventory_product_id ON public.inventory_movements(product_id);

-- ==============================================================================
-- 18. FUNCIONES Y TRIGGERS AUTOMÁTICOS
-- ==============================================================================

-- Función para actualizar rating y conteo de reseñas en products
CREATE OR REPLACE FUNCTION update_product_reviews_aggregate()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE public.products
    SET 
        rating = COALESCE((SELECT ROUND(AVG(rating)::numeric, 2) FROM public.reviews WHERE product_id = COALESCE(NEW.product_id, OLD.product_id) AND status = 'Aprobada'), 5.0),
        reviews_count = COALESCE((SELECT COUNT(*) FROM public.reviews WHERE product_id = COALESCE(NEW.product_id, OLD.product_id) AND status = 'Aprobada'), 0)
    WHERE id = COALESCE(NEW.product_id, OLD.product_id);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_reviews_aggregate ON public.reviews;
CREATE TRIGGER trg_update_reviews_aggregate
AFTER INSERT OR UPDATE OR DELETE ON public.reviews
FOR EACH ROW EXECUTE FUNCTION update_product_reviews_aggregate();

-- ==============================================================================
-- 19. ROW LEVEL SECURITY (RLS) Y POLÍTICAS UNIVERSALES
-- ==============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipping_zones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso universales
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN 
        SELECT table_name FROM information_schema.tables 
        WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Permitir acceso publico %I" ON public.%I', t, t);
        EXECUTE format('CREATE POLICY "Permitir acceso publico %I" ON public.%I FOR ALL USING (true) WITH CHECK (true)', t, t);
    END LOOP;
END $$;

-- ==============================================================================
-- 20. HABILITAR REALTIME (WebSockets en vivo para Supabase)
-- ==============================================================================
DO $$
BEGIN
    BEGIN
        ALTER PUBLICATION supabase_realtime ADD TABLE 
            public.products, 
            public.orders, 
            public.order_items, 
            public.cart_items, 
            public.reviews, 
            public.users, 
            public.coupons, 
            public.shipments;
    EXCEPTION
        WHEN duplicate_object THEN NULL;
    END;
END $$;

-- ==============================================================================
-- 21. DATOS SEMILLA (SEED DATA): ZONAS DE ENVÍO EN CARTAGENA
-- ==============================================================================
INSERT INTO public.shipping_zones (zone_code, name, neighborhoods, price, estimated_delivery_time, is_active)
VALUES
(
    'Z1',
    'Zona 1: Bocagrande, Castillogrande, El Laguito & Centro Histórico',
    '["Bocagrande", "Castillogrande", "El Laguito", "Centro Histórico", "Getsemaní", "San Diego", "La Matuna"]'::jsonb,
    6500.00,
    '2 a 4 horas',
    TRUE
),
(
    'Z2',
    'Zona 2: Manga, Pie de la Popa, Crespo, Marbella & Cabrero',
    '["Manga", "Pie de la Popa", "Crespo", "Marbella", "El Cabrero", "Torices", "Chambacú"]'::jsonb,
    7500.00,
    '3 a 6 horas',
    TRUE
),
(
    'Z3',
    'Zona 3: El Bosque, Los Alpes, Providencia, Santa Lucía & La Castellana',
    '["El Bosque", "Los Alpes", "Providencia", "Santa Lucía", "La Castellana", "San José de los Campanos", "Alto Bosque"]'::jsonb,
    8500.00,
    'Mismo día (4 a 8 horas)',
    TRUE
),
(
    'Z4',
    'Zona 4: Turbaco, Mamonal, Pasacaballos & Zona Conurbada',
    '["Turbaco", "Mamonal", "Pasacaballos", "Pontezuela", "Bayunca", "Manzanillo del Mar", "Arjona"]'::jsonb,
    12000.00,
    '24 horas',
    TRUE
)
ON CONFLICT (zone_code) DO UPDATE SET 
    name = EXCLUDED.name,
    neighborhoods = EXCLUDED.neighborhoods,
    price = EXCLUDED.price;

-- ==============================================================================
-- 22. DATOS SEMILLA: CATEGORÍAS
-- ==============================================================================
INSERT INTO public.categories (id, name, slug, icon, description, item_count)
VALUES
(1, 'Tecnología & Gadgets', 'electronics', 'bi-laptop', 'Smartphones, laptops, smartwatches y accesorios inteligentes en Cartagena', 42),
(2, 'Audio & Sonido', 'audio', 'bi-headphones', 'Auriculares bluetooth, altavoces portátiles y sonido envolvente', 28),
(3, 'Gaming & Videojuegos', 'gaming', 'bi-controller', 'Consolas PS5, teclados mecánicos, ratones gamer y periféricos esports', 35),
(4, 'Hogar & Climatización', 'home', 'bi-house-heart', 'Electrodomésticos, freidoras de aire, ventiladores y smarthome', 50),
(5, 'Calzado Deportivo', 'shoes', 'bi-lightning-charge', 'Zapatillas running, calzado deportivo transpirable y sneakers', 31),
(6, 'Moda & Accesorios', 'clothing', 'bi-bag-check', 'Mochilas antirrobo para portátil, gafas de sol y prendas urbanas', 48),
(7, 'Belleza & Cuidado', 'beauty', 'bi-stars', 'Cuidado personal, afeitadoras y kits de maquillaje profesional', 26),
(8, 'Herramientas & Bricolaje', 'tools', 'bi-tools', 'Taladros inalámbricos, sets de destornilladores y herramientas de precisión', 19)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    icon = EXCLUDED.icon;

-- ==============================================================================
-- 23. DATOS SEMILLA: USUARIOS DE CARTAGENA
-- ==============================================================================
INSERT INTO public.users 
(name, email, password_hash, role, avatar, phone, document_type, document_number, address, neighborhood, city, department, country, status)
VALUES
(
    'Alejandro Morales (SuperAdmin)',
    'admin@omnistore.com',
    'Admin*2026',
    'admin',
    './assets/images/avatar-placeholder.svg',
    '+57 (310) 845-9210',
    'CC',
    '1047482910',
    'Cra 3 # 7-15, Edificio Bocagrande Plaza',
    'Bocagrande',
    'Cartagena de Indias',
    'Bolívar',
    'Colombia',
    'active'
),
(
    'Sofía Valenzuela (Store Manager)',
    'vendor@omnistore.com',
    'Vendor*2026',
    'vendor',
    './assets/images/avatar-placeholder.svg',
    '+57 (315) 720-4491',
    'CC',
    '1143890214',
    'Av. Miramar # 24-80, Edificio Bahía Manga',
    'Manga',
    'Cartagena de Indias',
    'Bolívar',
    'Colombia',
    'active'
),
(
    'Carlos Mendoza (Cliente)',
    'cliente@omnistore.com',
    'Cliente*2026',
    'customer',
    './assets/images/avatar-placeholder.svg',
    '+57 (301) 630-1845',
    'CC',
    '1047392811',
    'Calle 70 # 4-18, Apto 502',
    'Crespo',
    'Cartagena de Indias',
    'Bolívar',
    'Colombia',
    'active'
),
(
    'Valeria Restrepo',
    'valeria.restrepo@gmail.com',
    'Valeria*2026',
    'customer',
    './assets/images/avatar-placeholder.svg',
    '+57 (318) 492-3301',
    'CC',
    '1050892341',
    'Cra 6 # 5-40, Castillogrande',
    'Castillogrande',
    'Cartagena de Indias',
    'Bolívar',
    'Colombia',
    'active'
)
ON CONFLICT (email) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    name = EXCLUDED.name,
    city = EXCLUDED.city,
    department = EXCLUDED.department;

-- ==============================================================================
-- 24. DATOS SEMILLA: CUPONES PROMOCIONALES
-- ==============================================================================
INSERT INTO public.coupons
(code, discount_type, discount_value, min_order_amount, max_uses, used_count, is_active, description)
VALUES
('BIENVENIDO50K', 'fixed', 50000.00, 200000.00, 1000, 42, TRUE, 'Bono de $50.000 COP en compras superiores a $200.000 COP en Cartagena'),
('CARTAGENA10', 'percentage', 10.00, 100000.00, 500, 118, TRUE, '10% de descuento en todo el catálogo de tecnología'),
('HEROICAPRO', 'percentage', 15.00, 300000.00, 200, 15, TRUE, '15% de descuento especial clientes OmniStore Cartagena'),
('ENVIOGRATISCTG', 'free_shipping', 0.00, 0.00, 2000, 340, TRUE, 'Domicilio gratis en toda Cartagena de Indias')
ON CONFLICT (code) DO UPDATE SET
    discount_value = EXCLUDED.discount_value,
    is_active = EXCLUDED.is_active;

-- ==============================================================================
-- 25. DATOS SEMILLA: CATÁLOGO DE PRODUCTOS EN PESOS COLOMBIANOS (COP $)
-- ==============================================================================
INSERT INTO public.products 
(id, name, sku, category_id, category_slug, category_label, brand, price, original_price, cost_price, discount_percent, stock, stock_left, stock_total, status, rating, reviews_count, sales_count, is_flash_deal, is_best_seller, has_free_shipping, badge_text, colors, sizes, description, tags)
VALUES
(
    101,
    'Auriculares Inalámbricos Pro Noise Cancelling Bluetooth 5.3',
    'AUDIO-TWS-PRO',
    2,
    'audio',
    'Audio & Auriculares',
    'Audio Pro',
    129000.00,
    389000.00,
    75000.00,
    67,
    45,
    14,
    100,
    'published',
    4.8,
    48,
    312,
    TRUE,
    TRUE,
    TRUE,
    'OFERTA RELÁMPAGO',
    '["Negro Mate", "Blanco Glaciar", "Azul Marino"]'::jsonb,
    '[]'::jsonb,
    'Cancelación activa de ruido híbrida de 40dB, batería de 38 horas con estuche de carga rápida tipo C, resistencia al agua IPX5 y micrófono HD para llamadas ultra claras. Entrega rápida en Cartagena.',
    '["audio", "bluetooth", "auriculares", "tws", "gadgets", "cartagena"]'::jsonb
),
(
    102,
    'Smartwatch Ultra AMOLED 1.96" Monitor Cardíaco & GPS Deportivo',
    'WATCH-ULTRA-GPS',
    1,
    'electronics',
    'Tecnología & Gadgets',
    'TechPro',
    195000.00,
    490000.00,
    110000.00,
    60,
    38,
    8,
    120,
    'published',
    4.9,
    64,
    480,
    TRUE,
    TRUE,
    TRUE,
    'TOP 1 CARTAGENA',
    '["Titanio Naranja", "Negro Obsidiana", "Verde Militar"]'::jsonb,
    '["45mm", "49mm"]'::jsonb,
    'Pantalla AMOLED de alta resolución siempre encendida, más de 100 modos deportivos, llamadas Bluetooth, sensor de oxígeno SpO2, monitor de sueño y autonomía de 10 días.',
    '["smartwatch", "reloj", "deportes", "fitness", "gps", "cartagena"]'::jsonb
),
(
    103,
    'Apple MacBook Pro M3 14" (16GB RAM / 512GB SSD) Gris Espacial',
    'APPLE-MBP-M3-14',
    1,
    'electronics',
    'Tecnología & Laptops',
    'Apple',
    7890000.00,
    8990000.00,
    6500000.00,
    12,
    12,
    3,
    20,
    'published',
    5.0,
    32,
    85,
    FALSE,
    TRUE,
    TRUE,
    'PREMIUM TECH',
    '["Gris Espacial", "Plata"]'::jsonb,
    '["14 pulgadas (512GB)", "14 pulgadas (1TB)"]'::jsonb,
    'Rendimiento profesional extremo con Chip M3 de Apple, pantalla Liquid Retina XDR de 120Hz, batería de hasta 22 horas y garantía oficial Apple Colombia de 1 año.',
    '["apple", "macbook", "laptop", "m3", "desarrollo", "cartagena"]'::jsonb
),
(
    104,
    'Sony PlayStation 5 Slim 1TB con Mando DualSense Blanco',
    'SONY-PS5-SLIM-1TB',
    3,
    'gaming',
    'Gaming & Consolas',
    'Sony',
    2490000.00,
    2890000.00,
    2100000.00,
    14,
    18,
    5,
    30,
    'published',
    4.9,
    56,
    210,
    TRUE,
    TRUE,
    TRUE,
    'GAMER CHOICE',
    '["Blanco Glaciar"]'::jsonb,
    '["Edición Digital", "Edición con Disco"]'::jsonb,
    'La consola más potente con SSD ultra rápido de 1TB, audio 3D Tempest, trazado de rayos y retroalimentación háptica en gatillos adaptativos DualSense.',
    '["ps5", "playstation", "sony", "gamer", "consolas", "cartagena"]'::jsonb
),
(
    105,
    'Sony WH-1000XM5 Auriculares Noise Canceling Líder del Mercado',
    'SONY-WH1000XM5-BLK',
    2,
    'audio',
    'Audio & Auriculares',
    'Sony',
    1450000.00,
    1790000.00,
    1150000.00,
    19,
    24,
    7,
    40,
    'published',
    4.9,
    42,
    140,
    FALSE,
    TRUE,
    TRUE,
    'SONIDO HI-RES',
    '["Negro Mate", "Plata Platino", "Azul Medianoche"]'::jsonb,
    '[]'::jsonb,
    'Cancelación de ruido líder en la industria con dos procesadores y 8 micrófonos, llamadas con IA nítidas, autonomía de 30 horas y soporte de audio Hi-Res LDAC.',
    '["sony", "audio", "noise-canceling", "bluetooth", "cartagena"]'::jsonb
),
(
    106,
    'Logitech G502 HERO Ratón Gamer Óptico 25K Sensor RGB',
    'LOGI-G502-HERO',
    3,
    'gaming',
    'Gaming & Periféricos',
    'Logitech',
    185000.00,
    260000.00,
    125000.00,
    29,
    55,
    18,
    80,
    'published',
    4.8,
    78,
    560,
    TRUE,
    TRUE,
    TRUE,
    'TOP GAMER',
    '["Negro Carbón"]'::jsonb,
    '[]'::jsonb,
    'Sensor HERO 25K de precisión submimétrica, 11 botones programables, sistema de pesas ajustables (5x 3.6g) e iluminación LIGHTSYNC RGB.',
    '["logitech", "mouse", "gamer", "esports", "pc", "cartagena"]'::jsonb
)
ON CONFLICT (sku) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    stock = EXCLUDED.stock,
    stock_left = EXCLUDED.stock_left,
    description = EXCLUDED.description;

-- ==============================================================================
-- 26. DATOS SEMILLA: PEDIDOS REGISTRADOS EN CARTAGENA
-- ==============================================================================
INSERT INTO public.orders 
(order_number, user_id, customer_name, customer_email, customer_phone, shipping_address, shipping_neighborhood, shipping_city, payment_method, item_count, subtotal, discount_amount, shipping_cost, total, status, order_date, items)
VALUES
(
    'OMNI-2026-84920',
    3,
    'Carlos Mendoza',
    'cliente@omnistore.com',
    '+57 (301) 630-1845',
    'Calle 70 # 4-18, Apto 502, Crespo',
    'Crespo',
    'Cartagena de Indias',
    'pse',
    2,
    6475000.00,
    50000.00,
    7500.00,
    6432500.00,
    'processing',
    CURRENT_DATE,
    '[{"name": "Apple MacBook Pro M3 14\"", "quantity": 1, "price": 7890000}, {"name": "Logitech G502 HERO", "quantity": 1, "price": 185000}]'::jsonb
),
(
    'OMNI-2026-84919',
    4,
    'Valeria Restrepo',
    'valeria.restrepo@gmail.com',
    '+57 (318) 492-3301',
    'Cra 6 # 5-40, Castillogrande',
    'Castillogrande',
    'Cartagena de Indias',
    'nequi',
    1,
    2490000.00,
    0.00,
    6500.00,
    2496500.00,
    'shipped',
    CURRENT_DATE - 1,
    '[{"name": "Sony PlayStation 5 Slim 1TB", "quantity": 1, "price": 2490000}]'::jsonb
),
(
    'OMNI-2026-84918',
    NULL,
    'Andrés Felipe Castro',
    'andres.castro@hotmail.com',
    '+57 (311) 554-9988',
    'Av. Miramar # 24-80, Manga',
    'Manga',
    'Cartagena de Indias',
    'card',
    1,
    1450000.00,
    0.00,
    7500.00,
    1457500.00,
    'delivered',
    CURRENT_DATE - 2,
    '[{"name": "Sony WH-1000XM5 Noise Canceling", "quantity": 1, "price": 1450000}]'::jsonb
)
ON CONFLICT (order_number) DO UPDATE SET
    status = EXCLUDED.status,
    total = EXCLUDED.total;

-- ==============================================================================
-- 27. DATOS SEMILLA: RESEÑAS EN CARTAGENA
-- ==============================================================================
INSERT INTO public.reviews
(product_id, user_id, author_name, author_email, author_city, rating, title, comment, is_verified_purchase, helpful_count, status)
VALUES
(103, 3, 'Carlos Mendoza', 'cliente@omnistore.com', 'Bocagrande, Cartagena', 5, 'Excelente máquina de desarrollo', 'Llegó en menos de 2 horas a Bocagrande en caja sellada con factura legal DIAN. Desempeño brutal para código y render.', TRUE, 34, 'Aprobada'),
(105, 2, 'Sofía Valenzuela', 'vendor@omnistore.com', 'Manga, Cartagena', 5, 'Sonido y cancelación impecables', 'El mejor sonido y cancelación de ruido para oficina. 100% original con garantía oficial de Sony Colombia en Cartagena.', TRUE, 22, 'Aprobada'),
(106, 1, 'Alejandro Morales', 'admin@omnistore.com', 'Crespo, Cartagena', 5, 'Ratón preciso y muy cómodo', 'Sensor excelente para gaming y productividad. El domicilio de OmniStore llegó puntual el mismo día.', TRUE, 18, 'Aprobada'),
(104, 4, 'Valeria Restrepo', 'valeria.restrepo@gmail.com', 'Castillogrande, Cartagena', 5, 'Envío súper rápido a Castillogrande', 'Empaque impecable con sellos de seguridad intactos. Muy feliz con la compra y el soporte por WhatsApp.', TRUE, 41, 'Aprobada');

-- ==============================================================================
-- 28. DATOS SEMILLA: CONFIGURACIÓN GENERAL (store_settings)
-- ==============================================================================
INSERT INTO public.store_settings (key, value)
VALUES
('general', '{
    "store_name": "OmniStore Cartagena",
    "nit": "901.849.201-4",
    "support_phone": "+57 (605) 665-9000",
    "whatsapp": "+57 310 845 9210",
    "support_email": "soporte@omnistore.com.co",
    "address": "Cra 3 # 7-15, Bocagrande, Cartagena de Indias, Bolívar",
    "currency": "COP",
    "timezone": "America/Bogota",
    "free_shipping_threshold": 150000
}'::jsonb),
('shipping', '{
    "default_carrier": "Domicilio Express Cartagena",
    "local_same_day": true,
    "pickup_point": "CEDI El Bosque, Cartagena"
}'::jsonb),
('tax', '{
    "iva_percentage": 19,
    "dian_resolution": "Res. DIAN No. 18764000001 (Rango FE-1 a FE-50000)",
    "regime": "Responsable de IVA - Régimen Común"
}'::jsonb)
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
